// <auto-generated />
using System;
using Machine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Machine.Data.Migrations.Tooling
{
    [DbContext(typeof(ToolingContext))]
    partial class ToolingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Machine.Data.Toolings.Tooling", b =>
                {
                    b.Property<int>("ToolingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Machine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tools")
                        .HasColumnType("TEXT");

                    b.HasKey("ToolingID");

                    b.ToTable("Toolings");
                });

            modelBuilder.Entity("Machine.Data.Toolings.ToolingUnit", b =>
                {
                    b.Property<int>("ToolingUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolHolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToolingID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ToolingUnitID");

                    b.HasIndex("ToolingID");

                    b.ToTable("ToolingUnits");
                });

            modelBuilder.Entity("Machine.Data.Toolings.ToolingUnit", b =>
                {
                    b.HasOne("Machine.Data.Toolings.Tooling", null)
                        .WithMany("Units")
                        .HasForeignKey("ToolingID");
                });

            modelBuilder.Entity("Machine.Data.Toolings.Tooling", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
